./node_modules/.bin/babel-node script/gen-static.js /airbnb/collect/
./node_modules/.bin/babel-node script/gen-static.js /closelyheld/act1/
./node_modules/.bin/babel-node script/gen-static.js /closelyheld/init/
./node_modules/.bin/babel-node script/gen-static.js /closelyheld/ref1/
./node_modules/.bin/babel-node script/gen-static.js /closelyheld/spec/
./node_modules/.bin/babel-node script/gen-static.js /consumer-protection/init/
./node_modules/.bin/babel-node script/gen-static.js /crowdfunding/act1/
./node_modules/.bin/babel-node script/gen-static.js /crowdfunding/init/
./node_modules/.bin/babel-node script/gen-static.js /crowdfunding/spec/
./node_modules/.bin/babel-node script/gen-static.js /cyberbullying/init/
./node_modules/.bin/babel-node script/gen-static.js /data-levy/act1/
./node_modules/.bin/babel-node script/gen-static.js /data-levy/init/
./node_modules/.bin/babel-node script/gen-static.js /data-levy/ref1/
./node_modules/.bin/babel-node script/gen-static.js /data-levy/spec/
./node_modules/.bin/babel-node script/gen-static.js /distant-education/init/
./node_modules/.bin/babel-node script/gen-static.js /distant-education/spec/
./node_modules/.bin/babel-node script/gen-static.js /eliquor/collect/
./node_modules/.bin/babel-node script/gen-static.js /etax/init/
./node_modules/.bin/babel-node script/gen-static.js /etax/spec/
./node_modules/.bin/babel-node script/gen-static.js /infosecurity/init/
./node_modules/.bin/babel-node script/gen-static.js /naming/collect/
./node_modules/.bin/babel-node script/gen-static.js /naming/init/
./node_modules/.bin/babel-node script/gen-static.js /personal-data-protection/init/
./node_modules/.bin/babel-node script/gen-static.js /personal-data-protection/ref1/
./node_modules/.bin/babel-node script/gen-static.js /personal-data-protection/spec/
./node_modules/.bin/babel-node script/gen-static.js /sandbox/collect/
./node_modules/.bin/babel-node script/gen-static.js /telemedicine/init/
./node_modules/.bin/babel-node script/gen-static.js /telework/init/
./node_modules/.bin/babel-node script/gen-static.js /uberx/collect/
